Add pile eval dataset
vllm-project/llm-compressor pull request #179
Opened 2024-09-18 00:25 UTC by rahul-tuli

SUMMARY:
This PR adds the pile eval dataset to llmcompressor

TEST PLAN:
Added unit test for loading + ran the following script to verify

```python
from llmcompressor.transformers import TextGenerationDataset, DataTrainingArguments
from transformers import AutoTokenizer

data_args = DataTrainingArguments(
            dataset="pile-eval",
            concatenate_data=True,
            splits={"calibration" : "validation[:1%]"},
        )
tokenizer = AutoTokenizer.from_pretrained("Xenova/llama2.c-stories15M")
dataset_manager = TextGenerationDataset.load_from_registry(
            data_args.dataset,
            data_args=data_args,
            split=data_args.splits,
            tokenizer=tokenizer,
        )

raw_dataset = dataset_manager.get_raw_dataset()
tokenized_dataset = dataset_manager.tokenize_and_process(
    raw_dataset, add_labels=True
)

```

2024-09-18 13:53 UTC, Satrat requested changes
just had a few nitpicky comments, also why do we call it PileEval? from the source it looks like its actually "PileVal"

2024-09-18 13:53 UTC, Satrat commented on src/llmcompressor/transformers/finetune/data/pile.py
> +    Child text generation class for the Open Platypus dataset
nit: docstring needs to be updated to reflect the correct dataset

2024-09-18 13:53 UTC, Satrat commented on tests/llmcompressor/transformers/finetune/data/test_registry.py
> +def test_pile_eval_initializes(tiny_llama_tokenizer):
Could you also add a test for loading and tokenizing a small subset to `test_dataset_loading.py`?

2024-09-29 20:52 UTC, kylesayrs approved these changes
LGTM

2024-10-18 02:09 UTC, markurtz commented on src/llmcompressor/transformers/finetune/data/pile.py
> +    Child text generation class for the Open Platypus dataset
```suggestion
    Child text generation class for the PileEval dataset
```

2024-10-18 02:09 UTC, markurtz approved these changes

2024-10-18 02:09 UTC, merged