Fix Weekly Test Failure
vllm-project/llm-compressor pull request #8
Opened 2024-06-25 19:38 UTC by Satrat

Original failure was from sparseml: https://github.com/neuralmagic/sparseml/actions/runs/9636050064/job/26573555739 

Issue was that when doing sparsity -> quantization, the quantization modifier needs to be included before SparseGPT. After restructuring the recipe the test passes locally for the 7b model. Also updating the device argument to be "auto" for all models

2024-06-25 19:57 UTC, bfineran approved these changes

2024-06-25 19:58 UTC, dsikka requested changes
Could we make sure `auto` works with the intended runner before we make this change?

2024-06-25 20:08 UTC, Satrat commented
> Could we make sure `auto` works with the intended runner before we make this change?

Sure, how would I test that? Right now I'm just setting `export CADENCE="weekly"` then running pytest on a kubernetes pod

2024-06-27 09:23 UTC, dbogunowicz approved these changes

2024-06-27 14:16 UTC, merged