Kylesayrs/gptq partition
vllm-project/llm-compressor pull request #914
Opened 2024-11-13 21:35 UTC by kylesayrs

2024-12-16 20:35 UTC, kylesayrs commented
https://github.com/neuralmagic/llm-compressor-testing/actions/runs/12359686271

2024-12-18 20:02 UTC, kylesayrs commented
No new nightly failures: https://github.com/neuralmagic/llm-compressor-testing/actions/runs/12398026591/job/34609853074

2024-12-28 20:22 UTC, dsikka commented
Is this ready for review?
If yes, can we update the PR description, show testing results, etc?

2024-12-29 16:22 UTC, kylesayrs commented
https://github.com/neuralmagic/llm-compressor-testing/actions/runs/12536961704

2025-01-02 03:28 UTC, kylesayrs commented
@dsikka The PR description has been updated and the PR is ready for review

2025-01-03 17:50 UTC, dsikka reviewed
Generally speaking, we should aim to keep PRs under <2k lines of code. 

For example, some of these changes could be introduced as follow-ups in smaller PRs, such as updates to examples or landing the first two pipelines and then following up with the tracing changes.

Some of the changes are also not necessarily vision model specific, such as removal of the GPTQ layer wrapper, which we could have potentially landed sooner to start.

2025-01-03 20:32 UTC, kylesayrs commented
@dsikka I'll note that 6K of those lines are copies of model definitions with slight modifications to enable tracing. For those files, we really only need to review the modifications. I'll make another commit to make the locations of those modifications clearer

2025-01-03 21:31 UTC, dsikka requested changes
Need to go through the tracing pipeline in more detail. 
It would also be helpful to understand the required changes to the models to make them compatible with tracing. Your diagram provides some insight but not 100% clear to me atm.

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/layer_sequential/helpers.py
> +                model(**batch)
If we're using multiple batches, i.e batch_size < dataset_size, the early stop would execute and return an intermediate output after the first batch from a layer which has not yet been quantized, correct? As _update_size by default is the entire dataset?

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +            if propagate_error:
I think for this particular pipeline, we should probably keep propagate_error=True as the only supported case/consider other cases as we expand data pipelines beyond GPTQ

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +class Subgraph:
docstring

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +def trace_subgraphs(
docstring

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +def get_tracer(
docstring

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +def partition_graph(model: Module, partitions: List[List[Node]]) -> List[Subgraph]:
dosctring

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/transformers/tracing/glm/LICENSE
> +1. 定义
this is needed for chatglm?

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/cache.py
> +class IntermediatesCache:
docstring

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +            run_sequential(
I think we need a more descriptive name to help better differentiate with the layer_sequential pipeline

2025-01-03 21:31 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/pipeline.py
> +            if propagate_error:
same as other pipeline, let's remove case for `propagate_error=False`

2025-01-03 22:59 UTC, kylesayrs commented
I've removed unnecessary model definitions and reduced the total changes by 3.5K lines

2025-01-03 23:06 UTC, kylesayrs commented on examples/multimodal_vision/llava_example.py
> +model = TracableLlavaForConditionalGeneration.from_pretrained(
#1032

2025-01-03 23:15 UTC, kylesayrs commented on src/llmcompressor/transformers/tracing/glm/LICENSE
> +1. 定义
Yes

2025-01-03 23:19 UTC, kylesayrs commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +            run_sequential(
I'm all ears for name suggestions. "sequential" is the term used by LC and AutoGPTQ to refer to the process of breaking a model into parts for the purpose of propagating error / reducing the number of active hessians.

"Layer Sequential Pipeline" and "Sequential Pipeline" were the most cogent names I could think of to describe this process at the time.

2025-01-03 23:25 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/pipeline.py
> +            if propagate_error:
Good idea

2025-01-03 23:30 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +            if propagate_error:
Good call

2025-01-03 23:39 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/helpers.py
> +                model(**batch)
If I'm reading your explanation correctly, then in most cases no.

If a modifier targets modules which execute before the first "layer" (for example, torch.nn.Embedding), then yes, that module would pass on outputs which do not propagate that module's compression error.

However, in most cases, we make the assumption that this is not the case.

We could fix this by running two forward passes (one calibration, one propagation) similar to the other layers, but this comes at considerable performance cost and is likely overkill for a non-default pipeline anyways.

2025-01-03 23:40 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/helpers.py
> +                model(**batch)
Thanks for the catch

2025-01-03 23:44 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/helpers.py
> +        for batch_index, batch in enumerate(tqdm.tqdm(dataloader, desc=desc)):
By default, [calibration data is batch_size=1](https://github.com/vllm-project/llm-compressor/blob/1b8c7bf1fa3999529fc36e701573effc5ffa6a66/src/llmcompressor/transformers/finetune/data/data_helpers.py#L54).

However, one of the effects of the data pipeline refactor is to allow users to choose batch_size in order to trade memory and runtime, similar to a normal training loop.

2025-01-03 23:48 UTC, kylesayrs commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +        if self._num_samples[module] >= self._update_size:
Example (update_size=3, dataset_size = 9)

1. make_empty_hessian + accumulate_hessian
2. accumulate_hessian
3. accumulate_hessian + quantize_weight
4. make_empty_hessian + accumulate_hessian
5. accumulate_hessian
6. accumulate_hessian + quantize_weight
7. make_empty_hessian + accumulate_hessian
8. accumulate_hessian
9. accumulate_hessian + quantize_weight

2025-01-03 23:51 UTC, kylesayrs commented
@dsikka Some common examples of untracable code and how to fix them are being detailed in https://github.com/vllm-project/llm-compressor/pull/1030

2025-01-03 23:53 UTC, kylesayrs commented on src/llmcompressor/pipelines/basic/pipeline.py
> +            model(**batch)
I'll add to the docstring

2025-01-03 23:54 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +    pipeline (see llmcompressor.pipelines.sequential)
Good idea

2025-01-06 18:23 UTC, dsikka commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +        if self._num_samples[module] >= self._update_size:
Ah makes sense. Sorry, missed the reset code at the bottom of the hook.

2025-01-06 19:20 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/pipeline.py
> +        intermediates = IntermediatesCache.from_dataloader(dataloader, model_device)
Why do we not need to capture the activations before the first subgraph, as we have to do with raising the early exception for the layer_sequential pipeline? Seems like the IntermediateCache is filled with values from the dataloader, not any previous activations.

2025-01-06 19:20 UTC, dsikka commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +            run_sequential(
Could we do "Layer Sequential" and "Subgraph Sequential" ?  Sequential being indicative of the data/error propagation while using "layer" and "subgraph" to differentiate between data structures?

2025-01-06 19:20 UTC, dsikka commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +        intermediates = capture_first_layer_intermediates(model, layers, dataloader)
nit for clarity:
```python
intermediates: IntermediatesCache = capture...
```

2025-01-06 19:20 UTC, dsikka commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +                        intermediates.update(batch_index, output)
Because this is primarily not going to be used by vision models, is there a need to offload/onload batches?

Do we have any data on the additional time it takes for running through the pipeline, with/without the offload?

2025-01-06 19:20 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/pipeline.py
> +                        intermediates.update(batch_index, output)
I would expect with vision models we have to offload batches. Just wondering if we have any data on change in performance when we offload to cpu? Or when combined with parts of the model being offloaded as well?

2025-01-06 19:20 UTC, dsikka commented on examples/multimodal_vision/llava_example.py
> +model = TracableLlavaForConditionalGeneration.from_pretrained(
For examples, could we add a case where the model is traceable without modifications?
Not urgent. Just as a follow-up if I didn't miss it in this PR

2025-01-06 19:25 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +        intermediates = capture_first_layer_intermediates(model, layers, dataloader)
Agree

2025-01-06 19:30 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +                        intermediates.update(batch_index, output)
Activation offloading as nothing to do with vision models. Activation offloading was done by the layer compressor.

Without activation offloading, the algorithm will have the same memory requirements as if we were running a forward pass of the model with `batch_size = ds_size` (which is to say, a lot)

2025-01-06 19:31 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/pipeline.py
> +                        intermediates.update(batch_index, output)
See https://github.com/vllm-project/llm-compressor/pull/914/files#r1904553406

2025-01-06 19:36 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/pipeline.py
> +        intermediates = IntermediatesCache.from_dataloader(dataloader, model_device)
The layer sequential pipeline processes everything before the first layer and captures the activations.

The sequential pipeline assigns everything before the first layer to the first subgraph. Said another way, all the processing that is done by `capture_first_layer_intermediates` is done in the sequential pipeline by processing the first subgraph.

```
subgraph[0] ~= capture_first_layer_intermediates
subgraph[1] ~= layer[0]
```

2025-01-06 19:41 UTC, kylesayrs commented on src/llmcompressor/pytorch/utils/helpers.py
> +    return tensors
Thanks for the catch, I believe we can remove this change (although it wouldn't hurt to keep it either).

During development I initially used this function offload/onload intermediates, but I implemented more robustly with the `IntermediatesCache`.

I think it makes sense to keep both functions. I'll remove this change and perform some regression tests to make sure everything still works.

2025-01-06 19:59 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +                        intermediates.update(batch_index, output)
> Activation offloading was done by the layer compressor

On main, we use activation offloading.
https://github.com/vllm-project/llm-compressor/blob/47bd37eee115687042c02d48784afc24c7e3b5ec/src/llmcompressor/modifiers/utils/pytorch_helpers.py#L29
https://github.com/vllm-project/llm-compressor/blob/47bd37eee115687042c02d48784afc24c7e3b5ec/src/llmcompressor/modifiers/utils/layer_compressor.py#L136

In this branch, we also use activation offloading. Therefore there is no change in performance due to there being no change in this regard.

2025-01-06 20:02 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +                        intermediates.update(batch_index, output)
I did a runtime regression a week ago and found that on the llama-8B model there was only about a 9% difference in runtime between main and this branch.

You can also see from the runtimes documented under the Winogrande Evaluations that the runtimes are reasonable.

2025-01-06 20:14 UTC, kylesayrs commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +            run_sequential(
I don't really like exposing the idea of subgraphs to the user, as most users won't have the context to really know what that means or why they should choose it.

In the future, the sequential pipeline will be the default for any recipes which include gptq, wanda, or sparsegpt. I'd prefer to keep this name short.

The layer sequential pipeline is only useful as a fallback for a small subset of models which follow layer-wise assumptions (next.input == prev.output) and are not traceable (due to weird or bad programming). The only model I've found like this is minicpm.

2025-01-06 20:41 UTC, kylesayrs commented on src/llmcompressor/pipelines/cache.py
> +            {
If you're referring to list compression, I agree. This function has about the same runtime with or without list comprehension, so let's remove it.

llama inputs
```
Preparing intermediates cache: 100%|███| 512/512 [00:00<00:00, 848.23it/s]  # with comp
Preparing intermediates cache: 100%|███| 512/512 [00:00<00:00, 860.89it/s]  # no comp
```

mllama inputs
```
Preparing intermediates cache: 100%|███| 20/20 [00:46<00:00,  2.31s/it]  # with comp
Preparing intermediates cache: 100%|███| 20/20 [00:46<00:00,  2.31s/it]  # no comp
```

2025-01-06 20:59 UTC, dsikka commented on examples/multimodal_vision/llava_example.py
> +model = TracableLlavaForConditionalGeneration.from_pretrained(
thanks

2025-01-06 21:10 UTC, kylesayrs commented on src/llmcompressor/pipelines/layer_sequential/pipeline.py
> +                        intermediates.update(batch_index, output)
Yeah happy to add any comments to make this clearer

2025-01-06 21:14 UTC, kylesayrs commented
https://github.com/neuralmagic/llm-compressor-testing/actions/runs/12640439996

2025-01-06 23:14 UTC, rahul-tuli approved these changes
Really like the IntermediatesCache implementation, good job!

<img src="https://media0.giphy.com/media/jmS6YojdAaYw5z1LHi/giphy.gif"/>

2025-01-06 23:14 UTC, rahul-tuli commented on src/llmcompressor/transformers/tracing/glm/LICENSE
> +The glm-4-9b License
Could you check if we need to add this to the manifest file? or will it get picked up in our wheels automatically?

2025-01-06 23:47 UTC, kylesayrs commented on src/llmcompressor/transformers/tracing/glm/LICENSE
> +The glm-4-9b License
I would not have caught that, thank you!

It is not included by default. After I added it to the manifest.in, you can verify that it is picked up as so:
```bash
python setup.py sdist
tar -tzf dist/llmcompressor-dev-0.3.1.dev0.tar.gz | grep LICENSE
```

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +            run_sequential(
hm let me think of other descriptors 
I think we just want each of the pipelines beyond the basic pipeline to be a little more verbose in its name

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    inside of sequential targets, ignored targets, or offloaded modules.
Trying to understand this comment. If the resulting tracer does not trace offloaded modules, how does this work for cases when we have parts of the model offloaded?

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    concrete_args = populate_concrete_args(model, sample_input)
populate_concrete_args is just creating a dictionary of defaults args?

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +        def create_arg(self, a: Any) -> Argument:
can you explain why this is needed?

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    assert check_assumption(graph.graph)
nit: update for a more descriptive name e.g check_graph_not_malformed or something

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +def match_modules(model: Module, target_names: List[str]) -> Set[Module]:
we seem to have multiple match_module methods.
https://github.com/vllm-project/llm-compressor/blob/153a4fa3c4d4831e01219b8d7a901366555bd960/src/llmcompressor/pipelines/layer_sequential/helpers.py#L21
We should either update their names, consolidate, make private or, nest if only used by one other method

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    # populate consumed_names according to when inputs are last used
what does this mean by "last used"?

2025-01-07 01:52 UTC, dsikka commented on src/llmcompressor/transformers/tracing/mllama.py
> +# TRACING: This function is not traceable
I think it would be helpful to have quick notes to help understand what you had to update to make this model traceable

2025-01-07 02:16 UTC, dsikka commented on examples/multimodal_vision/pixtral_example.py
> +input_ids = processor(text="Hello my name is", return_tensors="pt").input_ids.to("cuda")
Sample generation should probably be image related?

2025-01-07 03:29 UTC, kylesayrs commented on src/llmcompressor/modifiers/quantization/gptq/base.py
> +            run_sequential(
We do expose the idea of "tracing". Just something to think about, I'll sleep on it too

2025-01-07 03:49 UTC, mgoin reviewed
I think these Traceable model definitions have very opaque changes compared to the reference model definitions. This architecture seems like an intensive blocker to add support for a new model, as it requires a lot of knowledge of tracing limitations. However I understand the need - I'll look in more detail tomorrow

2025-01-07 03:49 UTC, mgoin commented on src/llmcompressor/pipelines/sequential/helpers.py
> +                # args and kwargs in function signature
Is this just explaining that you couldn't pass `*args, **kwargs` here?

2025-01-07 03:49 UTC, mgoin commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    inside of sequential targets, ignored targets, or offloaded modules.
What does the tracer actually trace?

2025-01-07 03:49 UTC, mgoin commented on src/llmcompressor/transformers/tracing/mistral.py
> +        self.post_init()
This looks to be the same as the modeling definition https://github.com/huggingface/transformers/blob/12ba96aa3cb3e4ed2a3ffb77b59f53f8ce9ac1fa/src/transformers/models/mistral/modeling_mistral.py#L752-L763
What is the purpose of this comment and code?

2025-01-07 04:17 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    concrete_args = populate_concrete_args(model, sample_input)
Yes, concrete args are essentially static flags and the set of all args that are not dynamically being traced.

Normally transformer's `trace` implementation automatically creates concrete args, but as noted in this function's description, `populate_concrete_args` also handles a bugged case where some models need to be provided default *args and **kwargs

2025-01-07 04:19 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    inside of sequential targets, ignored targets, or offloaded modules.
> Tracing within sequential targets and ignored targets is unnecessary, and tracing within offloaded modules may result in meta tensors being added to the model graph

When a module is "not traced", this means that the internals of module are not traced, but the module still appears in the graph as a `call_module` node.

2025-01-07 04:24 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    inside of sequential targets, ignored targets, or offloaded modules.
For example, in this model graph, the internals of `language_model_model_layers_39` are not traced (we don't see individual nodes for the attention mechanism, ffn, ect.) but all the operations after the module are traced with high granularity (we see individual `pow`, `.to` and `.dtype` functions).

<img width="529" alt="Screenshot 2025-01-06 at 23 22 15" src="https://github.com/user-attachments/assets/ab7295e5-6040-49c0-a6dd-f63e658ebe59" />

2025-01-07 04:27 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    inside of sequential targets, ignored targets, or offloaded modules.
As a side note, even if a module contains untraceable code internally, if the internals of the module skip tracing via `ignore` or `sequential_targets` or `has_offloaded_params`, then the model graph as a whole will still be traceable, but just with less granularity.

2025-01-07 04:38 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +        def create_arg(self, a: Any) -> Argument:
> special extension allows models which depend on config values to be traced

I overload this function to insert my own definition for creating an argument which is of type `PretrainedConfig`. Many models use values from the config during execution, but `torch.fx` is only capable of "baking" a limited set of class types into the model graph.

This code says, whenever the graph would try to reference an instance of a `PretrainedConfig` (for example, to get an attribute like `config.max_sequence_length`), instead just create a `PretrainedConfig` on the fly and initialize it with all of the args from the original config.

2025-01-07 04:39 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +        def create_arg(self, a: Any) -> Argument:
There are a few things in this file that we should consider upstreaming HF, this might be one of them

2025-01-07 04:48 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    # populate consumed_names according to when inputs are last used
Some input names are used by multiple subgraphs in the model (for example, the cross attention output is used by every text decoder layer in mllama) while other input names are only used once (for example, the hidden state of a text decoder layer).

All outputs are stored in the IntermediatesCache. However, we only want to keep outputs which will be later used as inputs to later subgraphs and vacate outputs which are never used again (this is really only to reduce cpu memory usage). Therefore, for each name, we need to find the index of the subgraph which is the last user of that name. After that, we can vacate that output from the cache.

Side note, outputs which do not lead to inputs are automatically pruned by the instantiation of `GraphModule`, and this is validated by `check_assumption`).

2025-01-07 04:50 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +def match_modules(model: Module, target_names: List[str]) -> Set[Module]:
I agree, I'll add a note to consolidate them later

2025-01-07 04:57 UTC, kylesayrs commented on src/llmcompressor/transformers/tracing/mllama.py
> +# TRACING: This function is not traceable
> what you had to update to make this model traceable

"what" I had to update to make this model traceable is exactly the code in this file. "why" and "where" it was done is indicated by the `# TRACING` comments

2025-01-07 05:00 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +                # args and kwargs in function signature
This is explaining why I need to write my own `populate_concrete_args` function rather than rely on [the one provided by transformers](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/fx.py#L1268-L1280)

2025-01-07 05:02 UTC, kylesayrs commented on src/llmcompressor/pipelines/sequential/helpers.py
> +    inside of sequential targets, ignored targets, or offloaded modules.
@mgoin The tracer traces all of the objects and operations that are need perform a forward pass of the model.

2025-01-07 05:06 UTC, kylesayrs commented on src/llmcompressor/transformers/tracing/mistral.py
> +        self.post_init()
That comments should say
```
# TRACING: Must use MistralModel with wrapped _prepare_4d_causal_attention_mask_with_cache_position function
```

Note that we define a version of the `MistralModel` which wraps the problematic function, and it is this definition that is used by `MistralForCausalLM`.

https://github.com/vllm-project/llm-compressor/pull/914/files/153a4fa3c4d4831e01219b8d7a901366555bd960#diff-75d8b6c11cbd2f8c8efbb720ba0566c4c895c4bbadeee774382f7fe7a4f6a3baR105-R106

2025-01-07 06:32 UTC, kylesayrs commented
@mgoin I think the [Tracing Guide](https://github.com/vllm-project/llm-compressor/pull/1030) will clarify how and why to make changes to your model to make it traceable and why tracing is the best and least invasive solution currently available.

Also note that
1. Unlike vllm, custom model definitions are not needed for every model. For the vast majority of text models, custom definitions are not required. Most vision models _when calibrated with text datasets_ also do not require custom tracing. Custom definitions are mostly required for vision models when calibrated with vision datasets, and even then some models like [phi3_vision](https://github.com/vllm-project/llm-compressor/pull/1032) do not require any changes.
2. Even if a text model is not traceable, gptq falls back to the layer_sequential pipeline, which is equivalent to what is currently on main. Therefore these changes only extend what is possible with llm-compressor now.

2025-01-07 17:57 UTC, kylesayrs commented on examples/multimodal_vision/pixtral_example.py
> +input_ids = processor(text="Hello my name is", return_tensors="pt").input_ids.to("cuda")
Will create follow up PR so we can land this asap

2025-01-07 22:59 UTC, dsikka approved these changes
Great work!

2025-01-08 19:21 UTC, rahul-tuli approved these changes

2025-01-08 21:48 UTC, mgoin approved these changes
Thanks for responding to comments, let's get to the followup items after this

2025-01-08 22:15 UTC, merged