Add Quantization then finetune tests
vllm-project/llm-compressor pull request #964
Opened 2024-12-09 17:47 UTC by horheynm

SUMMARY:
Add test to 
* Given a model, oneshot quantize, then run qat - training. 
Model must be run_compressed = False to run

2024-12-11 22:31 UTC, horheynm commented
/ready

2024-12-12 19:45 UTC, kylesayrs commented on tests/llmcompressor/transformers/finetune/test_oneshot_then_finetune.py
>      def test_oneshot_then_finetune(self):
test_sparsification_then_finetune

2024-12-12 19:46 UTC, kylesayrs commented on tests/llmcompressor/transformers/finetune/test_oneshot_then_finetune.py
>      def test_oneshot_then_finetune(self):
or move the recipe to an argument

parameterize or make functions, test_sparsification_then_finetune, test_quantization_then_finetune, test_oneshot_then_finetune, the latter is called by the first two

2025-01-09 19:55 UTC, kylesayrs approved these changes

2025-01-09 19:55 UTC, kylesayrs commented on tests/llmcompressor/transformers/finetune/test_oneshot_then_finetune.py
> +        # test reloading checkpoint and final model
Clarify that this is checking for checkpoint reloading

2025-01-10 18:09 UTC, kylesayrs approved these changes

2025-01-10 18:26 UTC, dsikka requested changes

2025-01-10 20:13 UTC, horheynm commented on src/llmcompressor/pytorch/utils/sparsification.py
> +        num_params = 0
This class doesnt have good tests in general. In the non-updated code, the run will generate an error, because `self.trainable_params[f"{name}.weight"]`, name might not be in self.traininable params. 
Ill revisit this when cleaning up the tests and updating more relevant tests

2025-01-10 20:50 UTC, kylesayrs approved these changes

2025-01-14 22:30 UTC, dsikka reviewed
LGTM. 

As per offline conversation, lets decompress before running finetune
and verify if we still need the skipif

2025-01-14 23:18 UTC, dsikka approved these changes
LGTM. please fix quality

2025-01-20 17:08 UTC, rahul-tuli submitted a review, later dismissed
LGTM

2025-01-20 17:21 UTC, kylesayrs reviewed
Need some clarification on `params_quantized`, otherwise LGTM!

2025-01-20 22:48 UTC, horheynm commented on src/llmcompressor/pytorch/utils/sparsification.py
> +        num_params = 0
I re ran the test but i dont see the error now. I do think its better to have this safeguard so i'm gonna keep this

2025-01-22 20:00 UTC, kylesayrs commented on src/llmcompressor/pytorch/utils/sparsification.py
> +            num_param_weight = torch.numel(
if getattr(layer, "weight", None) is not None:
    num_params += torch.numel(layer.weight)
if getattr(layer, "bias", None) is not None:
    num_params += torch.numel(layer.bias)

2025-01-22 20:54 UTC, kylesayrs approved these changes

2025-01-22 21:11 UTC, dsikka approved these changes

2025-01-23 00:47 UTC, merged