update test_run_compressed
vllm-project/llm-compressor pull request #970
Opened 2024-12-11 03:59 UTC by horheynm

SUMMARY:
Update run_compressed tests.
Note: Previous configs were comparing model.generate of a compressed quantized model and base model, so wrong setup of tests. Quantized model and base model will never generate the same.

2024-12-11 04:04 UTC, dsikka commented
The generations compared are decompressed and decompressed on the forward pass. So they should be close within a tolerance

2024-12-11 04:08 UTC, dsikka requested changes
I think you've changed the goal of the test which is compressed linear vs decompressing the whole model. We still want run_compressed to be  True for one of the models

2024-12-11 04:16 UTC, horheynm commented
> I think you've changed the goal of the test which is compressed linear vs decompressing the whole model. We still want run_compressed to be True for one of the models

Honestly, idk what the original test was doing. If you want to add compressed linear, decompressed model and its model.generate thats cool. 

original test is comparing a quantized model and a non-touched base model, that will always fail

2024-12-11 04:25 UTC, dsikka commented
> > I think you've changed the goal of the test which is compressed linear vs decompressing the whole model. We still want run_compressed to be True for one of the models
> 
> Honestly, idk what the original test was doing. If you want to add compressed linear, decompressed model and its model.generate thats cool.
> 
> original test is comparing a quantized model and a non-touched base model, that will always fail

1. We load a compressed model: 

https://github.com/vllm-project/llm-compressor/blob/606aab2b57eb0931f93976f6011f2b2869ebdc60/tests/llmcompressor/transformers/compression/test_run_compressed.py#L29

2. We create an empty model to hold the decompressed weights: 

https://github.com/vllm-project/llm-compressor/blob/606aab2b57eb0931f93976f6011f2b2869ebdc60/tests/llmcompressor/transformers/compression/test_run_compressed.py#L37

3) We then use lines 42-50 to decompress the whole model, using the empty model as the skeleton. This is loading the same checkpoint as what is used by the compressed model.
https://github.com/vllm-project/llm-compressor/blob/606aab2b57eb0931f93976f6011f2b2869ebdc60/tests/llmcompressor/transformers/compression/test_run_compressed.py#L42

We then run generations and compare the two cases. You're comparing decompressed in both cases, one is just decompressing on the forward pass.  It's the same checkpoint in both cases. 

We just want to update such that the uncompressed model can be decompressed using your new transformer changes.

Thi

2024-12-11 04:50 UTC, horheynm commented
Ok i see, we should update the test name, test_run_compressed is confusing

2024-12-11 22:31 UTC, horheynm commented
/ready

2024-12-17 00:55 UTC, dsikka requested changes
`test_run_compressed` is not testing the `run_compressed` arg which is the point of the test.

the input to both loads should be the same compressed model stub, with one of them being given the config to decompress the entire model as input

2025-01-10 18:34 UTC, dsikka requested changes

2025-01-10 18:34 UTC, dsikka commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +            QuantizationStatus.FROZEN
instead of doing this manual decompression, we should be using the AutoModel pathway to decompress?

2025-01-10 19:16 UTC, horheynm commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +            QuantizationStatus.FROZEN
Yeah thats more appropriate

2025-01-12 21:38 UTC, dsikka requested changes

2025-01-12 21:38 UTC, dsikka commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +
this docstring isn't very clear as to what is being tested.

2025-01-12 21:38 UTC, dsikka commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        )
we shouldn't need the code from lines 70-85. Scope of the test should be focused on the run_compressed vs decompressing everything upfront

2025-01-13 15:39 UTC, horheynm commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +
Yeah so thats happening. Not sure if you had a chance to look below but the test check thats happening is below here. 27-28. I can put these on top for better visibility

2025-01-14 20:56 UTC, dsikka approved these changes
these look great.
great work!

2025-01-14 20:56 UTC, dsikka commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        self.decompressed_model_manual = self.dense_model
why not just use self.dense_model in the test?

2025-01-14 20:58 UTC, horheynm commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        self.decompressed_model_manual = self.dense_model
Oh I can but its decompressed so i just want a name change. 
If we hit memory limitation I can use dense_model

2025-01-14 21:01 UTC, horheynm commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        self.decompressed_model_manual = self.dense_model
^ Actually models are pass by ref so should be ok

2025-01-14 21:16 UTC, mgoin approved these changes

2025-01-14 21:16 UTC, merged

2025-01-14 21:22 UTC, kylesayrs requested changes

2025-01-14 21:22 UTC, kylesayrs commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        assert not hasattr(
Should we not also check `decompressed_model_hf_quantizer`?

2025-01-14 21:22 UTC, kylesayrs commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        decompressed_model_manual = self.decompressed_model_manual.device
nit: `decompressed_model_manual` -> `manual_device`

2025-01-14 21:22 UTC, kylesayrs commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +            decompressed_model_manual_output = self.tokenizer.batch_decode(
nit: we don't actually have to decode the outputs. We can just compare the outputs directly

2025-01-14 21:22 UTC, kylesayrs commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        torch.cuda.empty_cache()
Please remove

2025-01-14 21:22 UTC, kylesayrs commented on tests/llmcompressor/transformers/compression/test_run_compressed.py
> +        breakpoint()
Please remove

2025-01-14 21:22 UTC, kylesayrs commented on tests/llmcompressor/transformers/compression/test_run_compressed.py
> +        decompressed_output = self.tokenizer.batch_decode(
Again, do not need to decode, only compare outputs

2025-01-14 21:22 UTC, kylesayrs commented on tests/llmcompressor/transformers/compression/test_run_compressed.py
> +        # overwrite weights in cpu to cuda
Why is this needed? It seems like you're already controlling which device the models live on when you load them.

2025-01-14 21:30 UTC, dsikka commented on tests/llmcompressor/transformers/compression/test_run_compressed.py
> +        decompressed_output = self.tokenizer.batch_decode(
this is fine to keep.

2025-01-14 21:35 UTC, horheynm commented on tests/llmcompressor/transformers/compression/test_run_compressed.py
> +        decompressed_output = self.tokenizer.batch_decode(
Kyle you are correct. I want to keep it to check if the generations make sense. If it takes up too much run time or memory happy to remove

2025-01-14 21:37 UTC, horheynm commented on tests/llmcompressor/transformers/compression/test_decompress.py
> +        assert not hasattr(
Sure, dense model wont have it so a check for that

2025-01-14 21:38 UTC, horheynm commented on tests/llmcompressor/transformers/compression/test_run_compressed.py
> +        # overwrite weights in cpu to cuda
At this point in the code, although set to cuda:N, I was getting an error of some layers not on the same device. I added that to override that.