fix conseq onehsot
vllm-project/llm-compressor pull request #971
Opened 2024-12-11 05:36 UTC by horheynm

SUMMARY:
* In multiple optimization tests, automatically decompress model if provided as optimized model
* Fix recipe stage length
* Revive old code

2024-12-11 22:31 UTC, horheynm commented
/ready

2025-01-10 20:39 UTC, dsikka requested changes

2025-01-10 20:39 UTC, dsikka commented on src/llmcompressor/transformers/utils/helpers.py
> +def is_model_quantized_from_path(path: str):
this seems redundant with the method we have in text_generation?

2025-01-10 21:16 UTC, rahul-tuli reviewed
Looks fine, I feel we can make a few functions cleaner by using pathlib. But I'll leave that upto you

2025-01-10 21:16 UTC, rahul-tuli commented on src/llmcompressor/transformers/utils/helpers.py
> +    :param RECIPE_FILE_NAME: The name of the recipe file to download.
Why is this in UPPERCASE?

2025-01-10 21:16 UTC, rahul-tuli commented on src/llmcompressor/transformers/utils/helpers.py
> +    :param recipe: the recipe to apply to the model.
nit: new line b/w description and params

2025-01-10 21:18 UTC, horheynm commented on src/llmcompressor/transformers/utils/helpers.py
> +def is_model_quantized_from_path(path: str):
sorry which method? 
is_model_quantized_from_path is defined here, text_generation.py uses it from here

2025-01-10 21:42 UTC, horheynm commented on src/llmcompressor/transformers/utils/helpers.py
> +    :param recipe: the recipe to apply to the model.
ok

2025-01-20 17:15 UTC, rahul-tuli approved these changes

2025-01-20 17:15 UTC, rahul-tuli commented on src/llmcompressor/transformers/utils/helpers.py
> +    Determine if model is quantized based on the config
docstring with params and return type?

2025-01-20 17:17 UTC, horheynm commented on src/llmcompressor/transformers/utils/helpers.py
> +    Determine if model is quantized based on the config
Ok

2025-01-20 17:25 UTC, rahul-tuli submitted a review, later dismissed
LGTM!

2025-01-20 17:30 UTC, kylesayrs requested changes
I believe the purpose of this test to test consecutive runs *without* model reloading.

There are quite a few helper functions which I'm not entirely convinced are needed as of now. I think it might be worth revisiting whether they're actually needed for these tests

2025-01-20 17:30 UTC, kylesayrs commented on src/llmcompressor/transformers/finetune/text_generation.py
> +    if is_model_quantized_from_path(model_path):
Is this helper `is_model_quantized_from_path` really necessary? What happens if you attempt to load a non-quantized model with `quantization_config=CompressedTensorsConfig(run_compressed=False)`?

2025-01-20 17:30 UTC, kylesayrs commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +quantization_config = CompressedTensorsConfig(run_compressed=False)
nit: consider moving into class, similar to other tests

2025-01-20 17:30 UTC, kylesayrs commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +        first_model = AutoModelForCausalLM.from_pretrained(
I think the purpose of this test to test consecutive runs *without* model reloading.

2025-01-20 17:35 UTC, dsikka commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +        first_model = AutoModelForCausalLM.from_pretrained(
The test currently loads the first oneshot model from disk when running the second oneshot run so the focus of this particular case is consecutive one shot runs after first loading from disk

2025-01-20 19:37 UTC, horheynm commented on src/llmcompressor/transformers/finetune/text_generation.py
> +    if is_model_quantized_from_path(model_path):
Good question, we do have is_model_quantzied in CT, but inputs a module. Here you check the config without loading. 
If you load a non-quantized model with the config, then It would error out -- but here on load it only adds the quant_config if its quantized. Its not a case we should worry about.

2025-01-20 19:40 UTC, horheynm commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +        first_model = AutoModelForCausalLM.from_pretrained(
We can do without reloading, but the original test on sparseml (if i remember correctly) was to load a saved model. As Dipika said above, we couldnt do that, bc HFQuantizer takes care of loading logic. 

The use case was that we optimize, save. Then we load from disk and optimize.

2025-01-20 19:40 UTC, horheynm commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +quantization_config = CompressedTensorsConfig(run_compressed=False)
ok

2025-01-22 20:39 UTC, kylesayrs submitted a review, later dismissed

2025-01-22 20:39 UTC, kylesayrs commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +        first_model = AutoModelForCausalLM.from_pretrained(
I misread the code

2025-01-22 21:17 UTC, dsikka commented on src/llmcompressor/transformers/utils/helpers.py
> +    config = AutoConfig.from_pretrained(path)
nit: check if also compressed-tensors as all quant models will have this quantization_config

2025-01-22 21:32 UTC, dsikka requested changes

2025-01-22 21:32 UTC, dsikka commented on src/llmcompressor/transformers/utils/helpers.py
> +    model_id_url = os.path.join(HUGGINGFACE_CO_URL_HOME, model_path)
can we target just downloading the recipe?

2025-01-22 21:32 UTC, dsikka commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +        recipe = infer_recipe_from_model_path(model_path=self.output_first)
Can you explain why we need this first recipe?
Seems like all `initialize_recipe` does is create the session and the pre_initialize_ method uses the recipe path, but is that doing anything here?

2025-01-22 21:41 UTC, dsikka commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
>          oneshot(
couldn't we just wrap  this with `with create_session()?`

2025-01-22 22:03 UTC, horheynm commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +        recipe = infer_recipe_from_model_path(model_path=self.output_first)
Yeah so we reset the session - if no reset the modifiers are finalized.
After reset, the recipe container is reset. We have a check at line 78 on this diff that checks the length of the applied recipes. 
Its not doing anthing else

2025-01-22 22:04 UTC, horheynm commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
>          oneshot(
Yeah we can

2025-01-22 22:11 UTC, kylesayrs submitted a review, later dismissed

2025-01-23 14:19 UTC, dsikka commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +            oneshot(
I am confused as to what we're doing here: 

1) We're creating a new session in `initialize_recipe` - my comment about using `with create_session()` was potentially about replacing `initialize_recipe`, not using both. Generally speaking, you dont need to wrap all the code, just the oneshot call

2) Why do we have `clear_sparse_session` set to False, while also creating a new session? Seems contradictory

2025-01-23 14:48 UTC, horheynm commented on src/llmcompressor/transformers/utils/helpers.py
> +    model_id_url = os.path.join(HUGGINGFACE_CO_URL_HOME, model_path)
yes it does

2025-01-23 14:59 UTC, horheynm commented on src/llmcompressor/transformers/utils/helpers.py
> +    config = AutoConfig.from_pretrained(path)
done!

2025-01-23 15:16 UTC, dsikka commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +            oneshot(
Two sessions are fine but they just be wrapping the oneshot call, not everything esle. I dont get the point of adding the `initialize_recipe` call though, if we're starting a new recipe/model for the second oneshot call.

2025-01-23 15:55 UTC, horheynm commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +            oneshot(
I see, I understand the comment. 
We run oneshot twice, so on save the change should be reflected in the recipe. 
After the first oneshot we get in `oneshot_output/test_2/recipe.yaml`
```yaml
test_stage_0:
  obcq_modifiers:
    SmoothQuantModifier:
      smoothing_strength: 0.5
      mappings:
      - - ['re:.*q_proj', 're:.*k_proj', 're:.*v_proj']
        - re:.*input_layernorm
      - - ['re:.*gate_proj', 're:.*up_proj']
        - re:.*post_attention_layernorm
    QuantizationModifier:
      ignore: [lm_head]
      config_groups:
        group_0:
          weights: {num_bits: 8}
          targets: [Linear]
    GPTQModifier: {block_size: 128}
    SparseGPTModifier:
      sparsity: 0.5
      block_size: 128
      sequential_update: false
      percdamp: 0.01
      mask_structure: 0:0
      targets: [model.layers.0]

```

and after with the current changes on the PR, we get 
```yaml
test_stage_0:
  obcq_modifiers:
    SmoothQuantModifier:
      smoothing_strength: 0.5
      mappings:
      - - ['re:.*q_proj', 're:.*k_proj', 're:.*v_proj']
        - re:.*input_layernorm
      - - ['re:.*gate_proj', 're:.*up_proj']
        - re:.*post_attention_layernorm
    QuantizationModifier:
      ignore: [lm_head]
      config_groups:
        group_0:
          weights: {num_bits: 8}
          targets: [Linear]
    GPTQModifier: {block_size: 128}
    SparseGPTModifier:
      sparsity: 0.5
      block_size: 128
      sequential_update: false
      percdamp: 0.01
      mask_structure: 0:0
      targets: [model.layers.0]
test_stage_1:
  obcq_modifiers:
    SparseGPTModifier:
      sparsity: 0.7
      block_size: 128
      sequential_update: true
      percdamp: 0.01
      mask_structure: 0:0
      targets: [model.layers.0]
      preserve_sparsity_mask: true

```

The goal of `initialize_recipe` is to add all the recipes that has been applied to the model on save. Without it, it will only have `test_stage_1`, not `test_stage_0`

2025-01-23 18:15 UTC, dsikka commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +            oneshot(
I see. Makes sense. Thanks for the explanation. Can you actually add a quick note to the test to with the recipe example?

And then update to remove the `with create_session()`

2025-01-23 20:27 UTC, horheynm commented on tests/llmcompressor/transformers/obcq/test_consecutive_runs.py
> +            oneshot(
Yup!

2025-01-23 23:59 UTC, merged